name: app
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  mobx: ^2.0.7+3
  flutter_mobx: ^2.0.6+1
  flutter_modular: ^5.0.3
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.4
  flutter_local_notifications: ^15.1.1
  flutter_native_splash: ^2.3.6
  flutter_svg: ^1.1.5
  share_plus: ^7.2.1
  asuka: ^2.0.0+1
  equatable:
  http:
  localstorage: ^4.0.0+1
  brasil_fields:
  url_launcher:
  mask_text_input_formatter:
  image_fade:
  package_info_plus:
  flutter_countdown_timer:
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  intl: ^0.18.1
  meta: ^1.10.0
  video_player: ^2.8.1
  camera: ^0.10.5+8
  dropdown_search: ^5.0.6
  shared_preferences: ^2.2.2
  chewie: ^1.7.4
  cached_network_image: ^3.3.1
  dio: ^5.4.0
  connectivity: ^3.0.6
  infinite_scroll_pagination: ^4.0.0
  flutter_html: ^3.0.0-beta.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  mobx_codegen: ^2.0.7

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # assets:
  # - assets/
  # - assets/img/
  # - assets/svg/
  # - assets/img/dix/

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
